  GNU nano 4.8                                                                                                                                                      docker-compose.yml                                                                                                                                                                 
version: "3.7"

networks:
  n8n:
     driver: bridge

services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    networks:
      - n8n
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${DATA_FOLDER}/caddy_data:/data
      - ${DATA_FOLDER}/caddy_config:/config
      - ${DATA_FOLDER}/caddy_config/Caddyfile:/etc/caddy/Caddyfile

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - n8n
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    command: redis-server
    networks:
      - n8n
    ports:
      - 6379:6379
  n8n:
    image: n8nio/n8n
    restart: always
    networks:
      - n8n
    ports:
      - 5678:5678
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER
      - N8N_BASIC_AUTH_PASSWORD
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=postgres
      - DB_POSTGRESDB_HOST=db
      - DB_POSTGRESDB_PASSWORD=postgres
      - DB_POSTGRESDB_USER=postgres
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=redis

    volumes:
      - ${DATA_FOLDER}/.n8n:/home/node/.n8n
      - ${DATA_FOLDER}/local_files:/files

  worker:
    image: n8nio/n8n
    restart: always
    networks:
      - n8n
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=postgres
      - DB_POSTGRESDB_HOST=db
      - DB_POSTGRESDB_PASSWORD=postgres
      - DB_POSTGRESDB_USER=postgres
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=redis
    command: n8n worker

volumes:
  caddy_data:
    external: true
  db:
    driver: local
  caddy_config:
